### ISSUE TITLE
Hi reddit

### ISSUE THREAD

**Issue by rainbowdash** [onbjerg/gitdrunk#1]
Came here from reddit. I'm currently running Mac OS 10.10.5 with node v0.12.7
`
dash:~ aaron$ npm install -g gitdrunk
/usr/local/bin/gitd -> /usr/local/lib/node_modules/gitdrunk/index.js
gitdrunk@1.0.4 /usr/local/lib/node_modules/gitdrunk
└── shelljs@0.5.3
dash:~ aaron$ gitd
env: node\r: No such file or directory
dash:~ aaron$ 
`

**Comment by onbjerg** [comment]
Hello. This happened to a friend of mine, too. It was because his installation was corrupted. Can you install other Node CLI tools globally and run them?

Try lenny, for example: ``npm install -g lenny && lenny``
